services:
  - type: web
    name: gta-free-stem-rails
    runtime: ruby
    plan: free
    rootDir: apps/web-rails
    buildCommand: bundle install && bin/rails assets:precompile
    startCommand: bin/rails db:migrate gta_free_stem:refresh && bin/rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
